// Code generated by "stringer -type sType fxsym.go"; DO NOT EDIT.

package fxsym

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SNone-0]
	_ = x[SProg-1]
	_ = x[SFunc-2]
	_ = x[SType-3]
	_ = x[SVar-4]
	_ = x[SConst-5]
}

const _sType_name = "SNoneSProgSFuncSTypeSVarSConst"

var _sType_index = [...]uint8{0, 5, 10, 15, 20, 24, 30}

func (i sType) String() string {
	if i < 0 || i >= sType(len(_sType_index)-1) {
		return "sType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sType_name[_sType_index[i]:_sType_index[i+1]]
}
